### PR TITLE
add at least one feature

### PR DESCRIPTION
**Pull request by algethamy**

### CODE REVIEW

**Comment by monooso** [comment]
Hi @efrontsa

Thanks for the pull request. I'm not sure what use-case it solves. It seems you could achieve the same thing using the existing functions. For example:

```php
new ApplyWhen(
  fn() => random_int(1, 10) % 2 === 0,
  array_rand(['required', 'string', 'min:10'])
);
```

Am I missing something?

Stephen

**Comment by algethamy** [comment]
I have a use case 

I have a national id number should follow one of the rules or throw an exception if not any one of the rules are applied on this number.

the rules are custom built so they are calling some services to make sure the candidate follows some criteria.


Thank you

**Comment by monooso** [comment]
Is there any reason you can't use `ApplyWhen` for that, as per [my previous comment](https://github.com/monooso/apposite/pull/10#issuecomment-729974184)?

**Comment by algethamy** [comment]
yes, `ApplyWhen` you can represent it as "AND" operator
`ApplyAtLeastOne` you can represent it as "OR" operator.

major differences between them.


```php
new ApplyAtLeastOne(auth()->check(), [
   new MustBeRegisteredAsAdmin,
   new UserAvailable,
]);
```

in this case, if admin or the user available should pass.

**Comment by monooso** [comment]
@efrontsa Ah, got you. Thanks for clarifying.

Something about this bothers me. It doesn't feel like it belongs in Apposite. I need to have a proper think about it.

**Pull request closed without merging**
